tserver: add lb_sourceranges test
Test to resrict external access using loadBalancerSourceRanges

diff --git a/tserver/default/bin/tserver_test b/tserver/default/bin/tserver_test
--- a/tserver/default/bin/tserver_test
+++ b/tserver/default/bin/tserver_test
@@ -47,6 +47,15 @@ cmd_tcase_vip_routes() {
 	tcase "Set VIP routes (ECMP)"
 	vip_route
 }
+##   tcase_vip_route <target-ipv4>
+##     Set the VIP route to the specified target
+cmd_tcase_vip_route() {
+	tcase "Set the VIP route to $1"
+	test -n "$1" || die "Parameter missing"
+	ip ro replace 10.0.0.0/24 via $1 || tdie ipv4
+	ip -6 ro replace $PREFIX:10.0.0.0/120 via $PREFIX:$1 || tdie ipv6
+}
+
 ##   tcase_start_tserver
 ##     Start tserver PODs
 cmd_tcase_start_tserver() {
@@ -65,14 +74,28 @@ cmd_tcase_create_svc() {
 	assign-lb-ip -svc tserver-udp -ip 10.0.0.52,$PREFIX:10.0.0.52
 	assign-lb-ip -svc tserver-sctp -ip 10.0.0.52,$PREFIX:10.0.0.52
 }
-##   tcase_mconnect
-##     Test external connectivity with mconnect
-cmd_tcase_external_traffic() {
-	tcase "Test external connectivity with mconnect"
-	external_traffic [$PREFIX:10.0.0.52]:5001
-	external_traffic 10.0.0.52:5001
+##   tcase_create_1svc <name> <vip>
+##     Create one service and assign lb-ip
+cmd_tcase_create_1svc() {
+	tcase "Create service $1 with vip $2"
+	test -n "$2" || tdie "Parameters missing"
+	local name=$1 vip=$2
+	local f=$yamld/$name.yaml
+	test -r $f || f=$yamld/svc-$name.yaml
+	kubectl create -f $f || die "kubectl create"
+	assign-lb-ip -svc $name -ip $vip,$PREFIX:$vip
 }
-external_traffic() {
+##   tcase_traffic [VIP]
+##     Test connectivity with mconnect
+cmd_tcase_traffic() {
+	local vip=10.0.0.52
+	test -n "$1" && vip=$1
+	tcase "Test connectivity with mconnect"
+	test_mconnect $vip:5001
+	echo $vip | grep -Eq '[a-z]+' && return 0  # Symbolic address
+	test_mconnect [$PREFIX:$vip]:5001
+}
+test_mconnect() {
 	pushv 30 6 5
 	if test -n "$__replicas"; then
 		tlog "Traffic to; $1, targets=$__replicas"
@@ -83,6 +106,26 @@ external_traffic() {
 		tex do_mconnect $1 || tdie "mconnect to; $1"
 	fi
 }
+##   tcase_deny_external_traffic <vip>
+##     Test that traffic to the vip is denied
+cmd_tcase_deny_external_traffic() {
+	tcase "Test that traffic to $1 is denied"
+	mkdir -p $tmp
+	local out=$tmp/out failed
+	mconnect -address 10.0.0.10:5001 -nconn 20 -output json > $out
+	failed=$(jq -r .failed_connects < $out)
+	if test "$failed" != "20"; then
+		cat $out
+		tdie "Ipv4: got [$failed] failed connects, expected 20"
+	fi
+	mconnect -address $PREFIX:10.0.0.10:5001 -nconn 20 -output json > $out
+	failed=$(jq -r .failed_connects < $out)
+	if test "$failed" != "20"; then
+		cat $out
+		tdie "Ipv4: got [$failed] failed connects, expected 20"
+	fi
+}
+
 ##   tcase_conntrack_size [size]
 ##     Set the conntrack table size. Default 20000
 cmd_tcase_conntrack_size() {
